name: Build and Test ASP.NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Cambiar según la versión usada en tu proyecto

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish for Deployment
      run: dotnet publish -c Release -o published/
